
CREATE TABLE IF NOT EXISTS reference_tables.landuse_classifications_scat (
        landuse_id VARCHAR PRIMARY KEY,
        description VARCHAR NOT NULL,
        level VARCHAR NOT NULL,
        parent_id VARCHAR,
        is_used BOOLEAN DEFAULT True
);

-- using top_crp_to_generated_codes
INSERT INTO reference_tables.landuse_classifications_scat
(landuse_id, description, level, parent_id, is_used)
VALUES
('CCRP_1', 'Accommodation & Food', 'order',NULL, True),
('CCRP_2', 'Agriculture, Forestry & Fishing', 'order',NULL, True),
('CCRP_3', 'Arts, Sport & Recreation', 'order',NULL, True),
('CCRP_4', 'Education', 'order',NULL, True),
('CCRP_5', 'Health', 'order',NULL, True),
('CCRP_6', 'Industry & Business', 'order',NULL, True),
('CCRP_7', 'Mining & Quarrying', 'order',NULL, True),
('CCRP_8', 'Other', 'order',NULL, True),
('CCRP_9', 'Professional, Scientific & Technical activities', 'order',NULL, True),
('CCRP_10', 'Public Admin, Defence & Security', 'order',NULL, True),
('CCRP_11', 'Retail', 'order',NULL, True),
('CCRP_12', 'Telecoms., Computing, Broadcasting & Publishing', 'order',NULL, True),
('CCRP_13', 'Transport & Storage', 'order',NULL, True),
('CCRP_14', 'Utilities', 'order',NULL, True),
('CCRP_15', 'Residential', 'order',NULL, True),
('CCRP_16','Places of Worship', 'order',NULL, True),
('???', 'unknown', 'order',NULL, True), -- for not yet classified ones

('1', 'AA/RAC Service Centres and Boxes', 'group','CCRP_8', True),
('3', 'Advertising Right', 'group','CCRP_9', True),
('4', 'Agricultural Showgrounds (National Scheme)', 'group','CCRP_11', True),
('5', 'Air Ports (Minor) (National Scheme)', 'group','CCRP_13', True),
('6', 'Air Strips (National Scheme)', 'group','CCRP_13', True),
('7', 'Aircraft Works With Airfields', 'group','CCRP_6', True),
('8', 'Airport Let Outs', 'group','CCRP_13', True),
('9', 'Aluminum Smelting Works', 'group','CCRP_6', True),
('10', 'Ambulance Stations', 'group','CCRP_10', True),
('11', 'Amusement Arcades', 'group','CCRP_3', True),
('12', 'Amusement Parks', 'group','CCRP_3', True),
('13', 'Animal Boarding', 'group','CCRP_9', True),
('14', 'Arenas', 'group','CCRP_3', True),
('15', 'Army Hereditaments', 'group','CCRP_10', True),
('16', 'Artificial Fibre Works', 'group','CCRP_6', True),
('17', 'Asphalt Plants', 'group','CCRP_6', True),
('18', 'ATMs', 'group','CCRP_6', True),
('19', 'Auction Rooms', 'group','CCRP_11', True),
('20', 'Baling Plants', 'group','CCRP_2', True),
('21', 'Banks/Insurance/Building Society Offices & Other A2 Uses', 'group','CCRP_6', True),
('22', 'Beach Huts', 'group','CCRP_1', True),
('23', 'Beet Sugar Factories', 'group','CCRP_6', True),
('24', 'Betting Offices', 'group','CCRP_3', True),
('25', 'Bingo Halls (National Scheme)', 'group','CCRP_3', True),
('26', 'Bird Sanctuaries', 'group','CCRP_3', True),
('27', 'Boat Yards', 'group','CCRP_6', True),
('28', 'Bowling Alleys', 'group','CCRP_3', True),
('29', 'Bowling Centres (Indoor)', 'group','CCRP_3', True),
('30', 'Bowling Greens (Outdoor)', 'group','CCRP_3', True),
('31', 'Breweries (National Scheme)', 'group','CCRP_6', True),
('32', 'Brickworks (Traditional), Clay Tile/Pipe Works', 'group','CCRP_6', True),
('33', 'Bulk Cement Storage Depots', 'group','CCRP_13', True),
('34', 'Bullion/Money Stores (National Scheme)', 'group','CCRP_6', True),
('35', 'Bus Garages', 'group','CCRP_13', True),
('36', 'Bus Stations', 'group','CCRP_13', True),
('37', 'Cable Head End Buildings', 'group','CCRP_12', True),
('38', 'Car Auction Buildings/Sites', 'group','CCRP_11', True),
('39', 'Car Parks (Multi-Storey)', 'group','CCRP_13', True),
('40', 'Car Parks (Surfaced Open)', 'group','CCRP_13', True),
('41', 'Car Parks (Unsurfaced Open)', 'group','CCRP_13', True),
('42', 'Car Showrooms', 'group','CCRP_11', True),
('43', 'Car Spaces', 'group','CCRP_13', True),
('44', 'Car Supermarkets', 'group','CCRP_11', True),
('45', 'Car Washes (Stand Alone)', 'group','CCRP_8', True),
('46', 'Car/Caravan Sales/Display/Hiring Sites', 'group','CCRP_11', True),
('47', 'Caravan Parks (Leisure) (National Scheme)', 'group','CCRP_1', True),
('48', 'Caravan Sites and Pitches (National Scheme)', 'group','CCRP_1', True),
('49', 'Casinos and Gambling Clubs', 'group','CCRP_3', True),
('50', 'Cattle Breeding Centres', 'group','CCRP_2', True),
('51', 'Cement Tile Works', 'group','CCRP_6', True),
('52', 'Cement Works', 'group','CCRP_6', True),
('53', 'Cemeteries (National Scheme)', 'group','CCRP_8', True),
('54', 'Chalet Parks (National Scheme)', 'group','CCRP_1', True),
('55', 'Chemical Works', 'group','CCRP_6', True),
('56', 'Cinemas (National Scheme)', 'group','CCRP_12', True),
('57', 'Civic and Public Buildings (Local Authority Occupations)', 'group','CCRP_10', True),
('58', 'Civic Amenity Sites', 'group','CCRP_10', True),
('59', 'Civil Airports', 'group','CCRP_13', True),
('60', 'Clubhouses', 'group','CCRP_3', True),
('61', 'Licensed Sports, Social & Private Members Clubs', 'group','CCRP_3', True),
('62', 'Inns', 'group','CCRP_1', True),
('63', 'Coking and Carbonising Plants', 'group','CCRP_6', True),
('64', 'Cold Stores', 'group','CCRP_13', True),
('65', 'Colleges of Further Education (National Scheme)', 'group','CCRP_4', True),
('66', 'Communication Stations (National Scheme)', 'group','CCRP_12', True),
('67', 'Community Day Centres', 'group','CCRP_5', True),
('68', 'Computer Centres (Non-Purpose Built)', 'group','???', True),
('69', 'Computer Centres (Purpose Built)', 'group','???', True),
('70', 'Concert Halls (National Scheme)', 'group','CCRP_3', True),
('71', 'Concrete Batching Plants', 'group','CCRP_6', True),
('72', 'Concrete Block Works', 'group','CCRP_6', True),
('73', 'Concrete Product Works', 'group','CCRP_6', True),
('74', 'Conference & Exhibition Centres', 'group','CCRP_6', True),
('75', 'Wedding & Function Venues', 'group','CCRP_8', True),
('76', 'Contractors Huts & Compounds', 'group','CCRP_6', True),
('77', 'Country House Hotels', 'group','CCRP_1', True),
('79', 'Creameries', 'group','CCRP_6', True),
('80', 'Crematoria (With & Without Cemeteries) (National Scheme)', 'group','CCRP_8', True),
('81', 'Cricket Centres', 'group','CCRP_3', True),
('82', 'Cricket Grounds (County)', 'group','CCRP_3', True),
('83', 'Cricket Grounds/Pitches (Non- County)', 'group','CCRP_3', True),
('84', 'Dance Schools & Centres', 'group','CCRP_4', True),
('85', 'Day Nurseries/Play Schools', 'group','CCRP_4', True),
('86', 'Departmental and Walk Round Stores (Large)', 'group','CCRP_11', True),
('87', 'Distilleries', 'group','CCRP_6', True),
('88', 'District Heating Undertakings & Networks', 'group','CCRP_14', True),
('89', 'Docks and Harbours (Non-Statutory)', 'group','CCRP_13', True),
('90', 'Domestic Fuel Installations', 'group','CCRP_14', True),
('91', 'Drive-In Restaurants', 'group','CCRP_1', True),
('92', 'Drive-Thru Restaurants', 'group','CCRP_1', True),
('93', 'Mine Water Treatment Plant and Premises', 'group','CCRP_14', True),
('94', 'Electricity Undertakings (Non- Statutory)', 'group','CCRP_14', True),
('95', 'Exhaust and Tyre Centres', 'group','CCRP_8', True),
('96', 'Factories, Workshops and Warehouses (Incl Bakeries & Dairies)', 'group','CCRP_6', True),
('97', 'Factory Shops', 'group','CCRP_11', True),
('98', 'Farm Shops', 'group','CCRP_11', True),
('99', 'Field Study, Activity and Adventure Centres', 'group','CCRP_4', True),
('100', 'Film and TV Studios', 'group','CCRP_12', True),
('101', 'Fire Stations', 'group','CCRP_10', True),
('102', 'Fish Farms', 'group','CCRP_2', True),
('103', 'Flour Mills (National Scheme)', 'group','CCRP_6', True),
('104', 'Food Courts', 'group','CCRP_1', True),
('105', 'Food Processing Centres', 'group','CCRP_6', True),
('106', 'Convenience Store', 'group','CCRP_11', True),
('107', 'Football Grounds', 'group','CCRP_3', True),
('108', 'Football Pitches', 'group','CCRP_3', True),
('109', 'Football Stadia', 'group','CCRP_3', True),
('110', 'Foundries', 'group','???', True),
('111', 'Funeral Parlours/Chapels Of Rest', 'group','CCRP_8', True),
('112', 'Game Farms', 'group','CCRP_2', True),
('113', 'Garages (Transport and Commercial)', 'group','CCRP_13', True),
('114', 'Garden Centres', 'group','CCRP_11', True),
('115', 'Gas Processing Plants', 'group','CCRP_14', True),
('116', 'Go Kart Rinks', 'group','CCRP_3', True),
('117', 'Golf Courses', 'group','CCRP_3', True),
('118', 'Golf Driving Ranges', 'group','CCRP_3', True),
('119', 'Grain Silos', 'group','CCRP_13', True),
('120', 'Granaries and Intervention Stores', 'group','CCRP_13', True),
('121', 'Greyhound Racetracks', 'group','CCRP_3', True),
('122', 'Guest & Boarding Houses', 'group','CCRP_1', True),
('123', 'Traveller Sites', 'group','CCRP_1', True),
('124', 'Hatcheries/Poultry Farms', 'group','CCRP_2', True),
('125', 'Health Farms', 'group','CCRP_5', True),
('126', 'Heliports', 'group','CCRP_13', True),
('127', 'Heredits Used For Primary Treatment/Processing Of Minerals', 'group','CCRP_7', True),
('128', 'Heritage Railways', 'group','CCRP_13', True),
('129', 'High Tech Warehouses', 'group','CCRP_13', True),
('130', 'Holiday Centres', 'group','CCRP_1', True),
('131', 'Holiday Homes (Self Catering)', 'group','CCRP_1', True),
('132', 'Horse Racecourses', 'group','CCRP_3', True),
('133', 'Hospital Let Outs', 'group','CCRP_6', True),
('134', 'Hospitals & Clinics NHS (National Scheme)', 'group','CCRP_5', True),
('135', 'Hospitals & Clinics (Private) (National Scheme)', 'group','CCRP_5', True),
('136', 'Hostels', 'group','CCRP_1', True),
('137', 'Hotels (3 Star And Under)', 'group','CCRP_1', True),
('138', 'Hotels (4 Star & Above) & Major Chain Operated ( includes 3* & above consortium hotels)', 'group','CCRP_1', True),
('139', 'Hypermarkets/Superstores (over 2500m²)', 'group','CCRP_11', True),
('140', 'Ice Rinks', 'group','CCRP_3', True),
('141', 'Interactive Telephone Kiosks', 'group','CCRP_12', True),
('142', 'Iron and/or Steel Works', 'group','CCRP_6', True),
('143', 'Kennels and Catteries', 'group','CCRP_9', True),
('144', 'Laboratories', 'group','CCRP_9', True),
('145', 'Lakes With Water Sport Facilities', 'group','CCRP_3', True),
('146', 'Land Used For Advertising', 'group','CCRP_9', True),
('147', 'Land Used For Car Boot Sales', 'group','CCRP_11', True),
('148', 'Land Used For Storage', 'group','CCRP_13', True),
('149', 'Landfill Gas Generator Sites', 'group','CCRP_14', True),
('150', 'Land used for Waste Composting', 'group','CCRP_14', True),
('151', 'Large Distribution Warehouses', 'group','CCRP_13', True),
('152', 'Large Food Stores (750 - 2500m²)', 'group','CCRP_11', True),
('153', 'Large Industrials (Over 20,000m²)', 'group','???', True),
('154', 'Large Shops (750 - 1850m²)', 'group','CCRP_11', True),
('155', 'Large Shops (Over 1850m²)', 'group','CCRP_11', True),
('156', 'Libraries', 'group','CCRP_3', True),
('157', 'Liquid Bulk Storage (Incl Petrol & Oil) (National Scheme)', 'group','CCRP_13', True),
('158', 'Livestock Markets (National Scheme)', 'group','CCRP_11', True),
('159', 'Local Authority Schools (National Scheme)', 'group','CCRP_4', True),
('160', 'Lodges (National Scheme)', 'group','CCRP_1', True),
('161', 'Lorry Parks', 'group','CCRP_13', True),
('162', 'Maltings - Non Trad', 'group','CCRP_6', True),
('163', 'Maltings - Trad', 'group','CCRP_6', True),
('164', 'Marinas (National Scheme)', 'group','CCRP_13', True),
('165', 'Markets (Other Than Livestock)', 'group','CCRP_11', True),
('166', 'Mineral Depot and Premises', 'group','CCRP_7', True),
('167', 'Mineral Producing Hereditament - Blockstone', 'group','CCRP_7', True),
('168', 'Mineral Producing Hereditament - Brine', 'group','CCRP_7', True),
('169', 'Mineral Producing Hereditament - Chalk', 'group','CCRP_7', True),
('170', 'Mineral Producing Hereditament - China Clay', 'group','CCRP_7', True),
('171', 'Mineral Producing Hereditament - Clay', 'group','CCRP_7', True),
('172', 'Mineral Producing Hereditament - Coal', 'group','CCRP_7', True),
('173', 'Mineral Producing Hereditament - Fluorspar', 'group','CCRP_7', True),
('174', 'Mineral Producing Hereditament - Gas', 'group','CCRP_7', True),
('175', 'Mineral Producing Hereditament - Hardrock', 'group','CCRP_7', True),
('176', 'Mineral Producing Hereditament - Inert', 'group','CCRP_7', True),
('177', 'Mineral Producing Hereditament - Oil', 'group','CCRP_7', True),
('178', 'Mineral Producing Hereditament - Other Mineral Category', 'group','CCRP_7', True),
('179', 'Mineral Producing Hereditament - Putrescible', 'group','CCRP_7', True),
('180', 'Mineral Producing Hereditament - Sand and Gravel', 'group','CCRP_7', True),
('181', 'Mineral Producing Hereditament - Sand', 'group','CCRP_7', True),
('182', 'Mineral Producing Hereditament - Shale Unburnt', 'group','CCRP_7', True),
('183', 'Mineral Producing Hereditament - Slate', 'group','CCRP_7', True),
('184', 'Mineral Producing Hereditament With Batching Plant', 'group','CCRP_7', True),
('185', 'Mineral Producing Hereditament With Coating Plant', 'group','???', True),
('186', 'Mineral Producing Heredtament With Tunnel Kiln', 'group','CCRP_6', True),
('187', 'MOD Hereditaments', 'group','CCRP_10', True),
('188', 'Model Villages', 'group','CCRP_3', True),
('189', 'Moorings (Floating Hereditaments)', 'group','CCRP_13', True),
('190', 'Mortuaries', 'group','CCRP_8', True),
('191', 'Motor Racetracks', 'group','CCRP_3', True),
('192', 'Motor Vehicle Works', 'group','CCRP_6', True),
('193', 'Motorway Service Area Let Outs', 'group','CCRP_13', True),
('194', 'Motorway and Major Road Service Areas', 'group','CCRP_13', True),
('195', 'Museums and Art Galleries (Contractors)', 'group','CCRP_3', True),
('196', 'Museums and Art Galleries (NonContractors)', 'group','CCRP_3', True),
('197', 'Navy Hereditaments', 'group','CCRP_10', True),
('198', 'Newspaper Printing Works (National Scheme)', 'group','CCRP_6', True),
('199', 'Night Clubs & Discotheques', 'group','CCRP_3', True),
('200', 'Nuclear Establishments', 'group','CCRP_6', True),
('201', 'Nursing Homes (Inc. Old Peoples Homes)', 'group','CCRP_5', True),
('202', 'Observatories', 'group','CCRP_9', True),
('203', 'Offices (Inc Computer Centres)', 'group','CCRP_9', True),
('204', 'Offices (Headquarters/Institutional)', 'group','CCRP_9', True),
('205', 'Oil Refineries', 'group','CCRP_6', True),
('206', 'Oxbridge Colleges', 'group','CCRP_4', True),
('207', 'Paper Mills', 'group','CCRP_6', True),
('208', 'Pavilions', 'group','CCRP_3', True),
('209', 'Petrol Filling Stations (National Scheme)', 'group','CCRP_11', True),
('210', 'Pharmacies', 'group','CCRP_11', True),
('211', 'Photographic Booths', 'group','CCRP_9', True),
('212', 'Pipelines', 'group','CCRP_13', True),
('213', 'Pleasure Piers', 'group','CCRP_3', True),
('214', 'Point to Point and Eventing Courses', 'group','CCRP_3', True),
('215', 'Police Stations', 'group','CCRP_10', True),
('216', 'Polo Grounds', 'group','CCRP_3', True),
('217', 'Post Office Sorting Centres', 'group','CCRP_13', True),
('218', 'Potteries', 'group','CCRP_6', True),
('219', 'Power Generators', 'group','CCRP_14', True),
('220', 'Prison Service Hereditaments', 'group','CCRP_10', True),
('221', 'Property used for Secondary Aggregate Processing', 'group','CCRP_14', True),
('222', 'Provender Mills (National Scheme)', 'group','CCRP_6', True),
('223', 'Public and Independent Schools (National Scheme)', 'group','CCRP_4', True),
('224', 'Public Conveniences (National Scheme)', 'group','CCRP_3', True),
('225', 'Public Halls', 'group','CCRP_3', True),
('226', 'Public Houses/Pub Restaurants (National Scheme)', 'group','CCRP_1', True),
('227', 'Public Houses/Pub Restaurants (Inc. Lodge) (National Scheme)', 'group','CCRP_1', True),
('228', 'Public Telephone Kiosks (National Scheme)', 'group','CCRP_12', True),
('229', 'Racing Stables (National Scheme)', 'group','CCRP_3', True),
('230', 'RAF Hereditaments', 'group','CCRP_10', True),
('231', 'Railways & Tramways (Non Leisure)', 'group','CCRP_13', True),
('232', 'Recording Studios', 'group','CCRP_12', True),
('233', 'Refuse Destructor Plants/Disposal Sites', 'group','CCRP_14', True),
('234', 'Restaurants', 'group','CCRP_1', True),
('235', 'Retail Warehouses and Foodstores', 'group','CCRP_11', True),
('236', 'Riding Schools & Livery Stables (National Scheme)', 'group','CCRP_4', True),
('237', 'Rifle and Weapons Ranges', 'group','CCRP_3', True),
('238', 'Roadside Restaurants (National Scheme)', 'group','CCRP_1', True),
('239', 'Roller Skating Rinks', 'group','CCRP_3', True),
('240', 'Royal Palaces', 'group','CCRP_3', True),
('241', 'Rugby League Grounds', 'group','CCRP_3', True),
('242', 'Rugby Union Grounds', 'group','CCRP_3', True),
('243', 'Sales Kiosks', 'group','CCRP_11', True),
('244', 'Scrap Metal/Breakers Yard', 'group','CCRP_6', True),
('245', 'Sea Dredged Aggregate Processing Plants & Depots', 'group','CCRP_6', True),
('246', 'Sewage Works (National Scheme)', 'group','CCRP_14', True),
('247', 'Ship Building Yards', 'group','CCRP_6', True),
('248', 'Ship Repair Yards', 'group','CCRP_6', True),
('249', 'Shops', 'group','CCRP_11', True),
('250', 'Showhouses (National Scheme)', 'group','CCRP_3', True),
('251', 'Showrooms', 'group','CCRP_11', True),
('252', 'Ski Centres', 'group','CCRP_3', True),
('253', 'Snooker Halls/Clubs', 'group','CCRP_3', True),
('254', 'Speedway Racetracks', 'group','CCRP_3', True),
('255', 'Spoil Heap Workings', 'group','CCRP_7', True),
('256', 'Sporting Rights', 'group','CCRP_3', True),
('257', 'Sports & Leisure Centres (LA) (Dry Only) (National Scheme)', 'group','CCRP_3', True),
('258', 'Sports & Leisure Centres (LA) (Wet & Dry) (National Scheme)', 'group','CCRP_3', True),
('259', 'Sports & Leisure Centres (Private)(Dry Only)', 'group','CCRP_3', True),
('260', 'Sports & Leisure Centres (Private)(Wet & Dry)', 'group','CCRP_3', True),
('261', 'Sports Grounds', 'group','CCRP_3', True),
('262', 'Sports Stadia', 'group','CCRP_3', True),
('263', 'Squash Courts', 'group','CCRP_3', True),
('264', 'Stables and Loose Boxes', 'group','CCRP_2', True),
('265', 'Stately Homes & Historic Houses (National Scheme)', 'group','CCRP_3', True),
('266', 'Station Let Outs', 'group','CCRP_6', True),
('267', 'Storage Depots', 'group','CCRP_13', True),
('268', 'Stores', 'group','CCRP_11', True),
('269', 'Stud Farms', 'group','CCRP_2', True),
('270', 'Studios', 'group','CCRP_8', True),
('271', 'Surgeries, Clinics, Health Centre (incl Dentists etc)', 'group','CCRP_5', True),
('272', 'Swimming Pools (Local Authority)', 'group','CCRP_3', True),
('273', 'Swimming Pools (Private)', 'group','CCRP_3', True),
('274', 'Tanneries', 'group','CCRP_6', True),
('275', 'Telecommunications Cable Networks (National Scheme)', 'group','CCRP_12', True),
('276', 'Telecommunications Switching Centres', 'group','CCRP_12', True),
('277', 'Tennis Centres', 'group','CCRP_3', True),
('278', 'Tennis Courts/Clubs', 'group','CCRP_3', True),
('279', 'Theatres (National Scheme)', 'group','CCRP_3', True),
('280', 'Theme Parks', 'group','CCRP_3', True),
('281', 'Timeshare Complexes (National Scheme)', 'group','CCRP_1', True),
('282', 'Tolls (Ferries, Roads And Bridges)', 'group','CCRP_13', True),
('283', 'Totalisators On Horse Racecourses', 'group','CCRP_3', True),
('284', 'Tourist Attractions/Dark Rides', 'group','CCRP_3', True),
('285', 'Training Centre (Non Residential)', 'group','CCRP_4', True),
('286', 'Training Centre (Residential)', 'group','CCRP_4', True),
('287', 'Truck Stops', 'group','CCRP_13', True),
('288', 'Universities (Excluding Oxbridge) (National Scheme)', 'group','CCRP_4', True),
('289', 'Vehicle Repair Workshops & Garages', 'group','CCRP_8', True),
('290', 'Vehicle Testing Centres (With Test Tracks)', 'group','CCRP_9', True),
('291', 'Vehicle Testing Centres (Without Test Tracks)', 'group','CCRP_9', True),
('292', 'Veterinary Clinics / Animal Clinics', 'group','CCRP_9', True),
('293', 'Village Halls, Scout Huts, Cadet Huts Etc', 'group','CCRP_8', True),
('294', 'Vineyards/Wineries', 'group','CCRP_2', True),
('295', 'Wafer Fabrications (National Scheme)', 'group','CCRP_6', True),
('296', 'War Games Courses/Misc Ag. Use', 'group','CCRP_3', True),
('297', 'Waste Incinerator Plants', 'group','CCRP_14', True),
('298', 'Waste Recycling Plants', 'group','CCRP_14', True),
('299', 'Waste Transfer Stations', 'group','???', True),
('300', 'Water Undertakings (Non-Statutory)', 'group','CCRP_14', True),
('301', 'Wholesale Warehouses', 'group','CCRP_13', True),
('302', 'Windmills', 'group','CCRP_14', True),
('303', 'Wine Bars', 'group','CCRP_1', True),
('304', 'Zoos & Safari Parks', 'group','CCRP_3', True),
('400', 'Abattoirs & Slaughter Houses (Contractors Valuation)', 'group','CCRP_6', True),
('401', 'Abattoirs & Slaughter Houses (Rental Valuation)', 'group','CCRP_6', True),
('402', 'Agricultural Research Centres', 'group','CCRP_9', True),
('403', 'Aquaria', 'group','CCRP_3', True),
('404', 'Archives', 'group','CCRP_3', True),
('405', 'Boathouses', 'group','CCRP_13', True),
('406', 'Bus Garages (Contractors Valuation)', 'group','CCRP_13', True),
('407', 'Bus Garages (Rental Valuation)', 'group','CCRP_13', True),
('408', 'Business Units', 'group','CCRP_6', True),
('409', 'Cafes', 'group','CCRP_1', True),
('410', 'Changing Rooms', 'group','CCRP_3', True),
('411', 'Coastguard Stations', 'group','CCRP_10', True),
('412', 'Cold Stores (Contractors Valuation)', 'group','CCRP_13', True),
('413', 'Cold Stores (Rental Valuation)', 'group','CCRP_13', True),
('414', 'Courts (Contractors Valuation)', 'group','CCRP_10', True),
('415', 'Courts (Rental Valuation)', 'group','CCRP_10', True),
('416', 'Gymnasia/Fitness Suites', 'group','CCRP_3', True),
('417', 'Hairdressing/Beauty Salons', 'group','CCRP_8', True),
('418', 'Information/Visitor Centres', 'group','CCRP_6', True),
('419', 'Land Used for Display', 'group','CCRP_9', True),
('420', 'Lifeboat Stations', 'group','CCRP_10', True),
('421', 'Miniature Railways', 'group','CCRP_3', True),
('422', 'Pack Houses', 'group','CCRP_6', True),
('423', 'Peat Fields', 'group','CCRP_7', True),
('424', 'Pet Grooming Parlours', 'group','CCRP_8', True),
('425', 'Pharmacies Within/Adjacent to Surgery/Health Centre', 'group','CCRP_11', True),
('426', 'Pitch and Putt/Putting Greens', 'group','CCRP_3', True),
('427', 'Pitches for Stalls, Sales or Promotions', 'group','CCRP_11', True),
('428', 'Police Training Colleges', 'group','CCRP_4', True),
('429', 'Post Offices', 'group','CCRP_13', True),
('430', 'Pumping Mines', 'group','CCRP_7', True),
('431', 'Religious Retreats/Study Centres (Residential)', 'group','CCRP_8', True),
('432', 'Sales Offices', 'group','CCRP_6', True),
('433', 'Statutory Docks and Harbours (Formula)', 'group','CCRP_13', True),
('434', 'Statutory Docks and Harbours (Non- Formula, Prescribed)', 'group','CCRP_13', True),
('435', 'Statutory Docks and Harbours (Other)', 'group','CCRP_13', True),
('436', 'Surgeries, Clinics, Health Centres (Contractors Valuation)', 'group','CCRP_5', True),
('437', 'Surgeries, Clinics, Health Centres (Rental Valuation)', 'group','CCRP_5', True),
('438', 'Telescope Sites', 'group','CCRP_9', True),
('439', 'University - Ancillary Land or Buildings', 'group','CCRP_4', True),
('440', 'University Occupation Within Hospitals', 'group','CCRP_4', True),
('441', 'Weighbridges', 'group','CCRP_13', True),
('442', 'Takeaway Food Outlet (Predominantly Off Premises)', 'group','CCRP_1', True),
('500', 'Cafes/Restaurants Within/Part of Specialist Property', 'group','CCRP_1', True),
('501', 'Car Parking Within/Part of Specialist Property', 'group','CCRP_13', True),
('502', 'Garages Within/Part of Specialist Property', 'group','CCRP_13', True),
('503', 'Gymnasia/Fitness Suites Within/Part of Specialist Property', 'group','CCRP_3', True),
('504', 'Kiosks Within/Part of Specialist Property', 'group','CCRP_11', True),
('505', 'Nurseries/Creches Within/Part of Specialist Property', 'group','CCRP_4', True),
('506', 'Offices Within/Part of Specialist Property', 'group','CCRP_6', True),
('507', 'Salons/Clinics Within/Part of Specialist Property', 'group','CCRP_8', True),
('508', 'Shops Within/Part of Specialist Property', 'group','CCRP_11', True),
('509', 'Sports & Leisure Centres Within/Part of Specialist Property', 'group','CCRP_3', True),
('510', 'Stores Within/Part of Specialist Property', 'group','CCRP_11', True),
('511', 'Warehouses Within/Part of Specialist Property', 'group','CCRP_13', True),
('512', 'Workshops Within/Part of Specialist Property', 'group','CCRP_6', True),
('513', 'Miscellaneous Within/Part of Specialist Property', 'group','???', True),
('700', 'Sponsored Roundabout Advertising Displays', 'group','CCRP_9', True),
('701', 'Restaurant With Letting Accomodation', 'group','CCRP_1', True),
('702', 'Driving Standards Agency Centre', 'group','CCRP_9', True),
('703', 'Residual Shopping Mall', 'group','CCRP_11', True),
('704', 'Land Used For Seasonal Markets & Events', 'group','CCRP_11', True),
('705', 'Market Stall (Not Pitch)', 'group','CCRP_11', True),
('706', 'Advertising Displays On Pavements & Bus Shelters', 'group','CCRP_9', True),
('707', 'Advertising Displays At Superstores', 'group','CCRP_9', True),
('708', 'Advertising Displays From Phone Booths', 'group','CCRP_9', True),
('709', 'Dark Retailing/Internet Sites', 'group','CCRP_11', True),
('710', 'Residual Mall', 'group','CCRP_11', True),
('711', 'Advertising Displays From Agricultural Land', 'group','CCRP_9', True),
('712', 'Rail Freight Depots', 'group','CCRP_13', True),
('713', 'Bicycle Folding Box Site', 'group','CCRP_13', True),
('714', 'Rail Maintenance Depots', 'group','CCRP_13', True),
('715', 'Football Training Grounds', 'group','CCRP_3', True),
('716', 'Cafe/Restaurants Within/Part of NonSpecialist Properties', 'group','CCRP_1', True),
('717', 'Delivery Box Site & Premises', 'group','CCRP_13', True),
('718', 'Electric Charge Stations', 'group','CCRP_13', True),
('719', 'Car Washes (Stand Alone - Hand Car Wash)', 'group','CCRP_8', True),
('720', 'LPG Service Station', 'group','CCRP_11', True),
('721', 'Self Storage Facility', 'group','CCRP_13', True),
('722', 'Serviced Appartments', 'group','CCRP_1', True),
('723', 'Serviced Offices', 'group','CCRP_6', True),
('724', 'Street Points (eg Cycle Docking Stations)', 'group','CCRP_13', True),
('725', 'Park & Ride Car Parks', 'group','CCRP_13', True),
('726', 'Telecommunications Large Broadcast Sites', 'group','CCRP_12', True),
('727', 'Waste Anaerobic Digestion Plants', 'group','CCRP_14', True),
('728', 'Bagging Plant & Premises', 'group','CCRP_6', True),
('729', 'Renewable Generators - Mixed Technologies', 'group','CCRP_14', True),
('730', 'Biomass Biological (Crop & Slurry Based Anaerobic Digestors, Incl Gas to Grid)', 'group','CCRP_14', True),
('731', 'Biomass Thermal (Incl Combustion, Gasification and Pyrolysis)', 'group','CCRP_14', True),
('732', 'Click & Collect Locker Site', 'group','CCRP_13', True),
('733', 'Battery Store', 'group','CCRP_11', True),
('734', 'Wedding and Function Venue', 'group','CCRP_8', True),
('735', 'Historic Property (National Trust/English Heritage)', 'group','CCRP_3', True),
('736', 'Holiday Home Self Catering (Complexs)', 'group','CCRP_1', True),
('737', 'Ferry Terminal', 'group','CCRP_13', True),
('738', 'Builders Merchant', 'group','CCRP_6', True),
('739', 'Soccer Centres', 'group','CCRP_3', True),
('740', 'Secure Childrens Homes', 'group','CCRP_5', True),
('741', 'Independent Gas Transport (IGT)', 'group','CCRP_14', True),
('742', 'Independent Distribution Network Operators (IDNO)', 'group','CCRP_14', True),
('743', 'Renewable Power Generators - Photovoltaic', 'group','CCRP_14', True),
('744', 'Renewable Power Generators – Wind', 'group','CCRP_14', True),
('745', 'Renewable Power Generators – Other', 'group','CCRP_14', True),
('746', 'Renewable Power Generators - Hydro', 'group','CCRP_14', True),
('747', 'Fossil Fuel Power Stations', 'group','CCRP_14', True),
('748', 'Nuclear Power Stations', 'group','CCRP_14', True),
('749', 'Underground Gas Storage Facility', 'group','CCRP_14', True),
('750', 'NHS Clinics & Health Centres (Contractors)', 'group','CCRP_5', True),
('751', 'NHS Clinics & Health Centres (Rentals)', 'group','CCRP_5', True),
('752', 'Surgeries (Other Than GP/NHS) (Contractors)', 'group','CCRP_5', True),
('753', 'Surgeries (Other Than GP/NHS) (Rentals)', 'group','CCRP_5', True),
('754', 'GP Surgeries (Contractors)', 'group','CCRP_5', True),
('755', 'GP Surgeries (Rentals)', 'group','CCRP_5', True),
('756', 'Equestrian Hospitals', 'group','CCRP_9', True),
('757', 'Plant Nurseries', 'group','CCRP_2', True),
('992', 'Commercial Miscellaneous', 'group','???', True),
('993', 'Leisure Miscellaneous', 'group','CCRP_3', True),
('994', 'Industrial Miscellaneous', 'group','CCRP_6', True),
('995', 'Educational Miscellaneous', 'group','CCRP_4', True),
('996', 'Formula Assessed Miscellaneous', 'group','???', True),
('997', 'Minerals Miscellaneous', 'group','CCRP_7', True),
('998', 'Crown Miscellaneous', 'group','CCRP_10', True),
('999', 'Miscellaneous', 'group','CCRP_8', True),
('EXTENSION_1', 'Abbeys', 'group', 'CCRP_16', True),
('EXTENSION_2', 'Cathedrals', 'group', 'CCRP_16', True),
('EXTENSION_3', 'Chapels', 'group', 'CCRP_16', True),
('EXTENSION_4', 'Churches', 'group', 'CCRP_16', True),
('EXTENSION_5', 'Dargahs', 'group', 'CCRP_16', True),
('EXTENSION_6', 'Gurdwaras', 'group', 'CCRP_16', True),
('EXTENSION_7', 'Halls', 'group', 'CCRP_16', True),
('EXTENSION_8', 'Mandirs', 'group', 'CCRP_16', True),
('EXTENSION_9', 'Mausolea/Large Tombs', 'group', 'CCRP_16', True),
('EXTENSION_10', 'Meeting Houses', 'group', 'CCRP_16', True),
('EXTENSION_11', 'Monasteries', 'group', 'CCRP_16', True),
('EXTENSION_12', 'Mosques', 'group', 'CCRP_16', True),
('EXTENSION_13', 'Synagogues', 'group', 'CCRP_16', True),
('EXTENSION_14', 'Temples', 'group', 'CCRP_16', True),
('EXTENSION_15', 'Other Spiritual Sites', 'group', 'CCRP_16', True),
('EXTENSION_16', 'Dwelling/Single-family home', 'group', 'CCRP_15', True),
('EXTENSION_17', 'Dwelling/Building with multiple flats', 'group', 'CCRP_15', True),
('EXTENSION_18', 'Residential Institutions', 'group', 'CCRP_15', True),
('EXTENSION_19', 'Residential Garden Buildings', 'group', 'CCRP_15', True);

CREATE TABLE IF NOT EXISTS reference_tables.buildings_landuse_order_scat AS
SELECT a.landuse_id,
       a.description
FROM reference_tables.landuse_classifications_scat a
WHERE a.level = 'order'
  AND a.is_used;

ALTER TABLE reference_tables.buildings_landuse_order_scat
ADD UNIQUE (description);


CREATE TABLE IF NOT EXISTS reference_tables.buildings_landuse_group_scat AS
SELECT a.landuse_id,
       a.description,
       a.parent_id AS parent_order_id
FROM reference_tables.landuse_classifications_scat a
WHERE a.level = 'group'
  AND a.is_used;

ALTER TABLE reference_tables.buildings_landuse_group_scat
ADD UNIQUE (description);


-- Land use order, singular. Client and db constrained with foreign key
ALTER TABLE buildings
  ADD COLUMN IF NOT EXISTS current_landuse_order_scat text,
  ADD FOREIGN KEY (current_landuse_order_scat)
  REFERENCES reference_tables.buildings_landuse_order_scat (description);


-- Land use groups, array. Derived from classes.
ALTER TABLE buildings
  ADD COLUMN IF NOT EXISTS current_landuse_group_scat text ARRAY[41];

-- verification for landuse
ALTER TABLE buildings ADD COLUMN IF NOT EXISTS current_landuse_scat_source varchar;
ALTER TABLE buildings ADD CONSTRAINT buildings_current_landuse_scat_source_len CHECK (length(current_landuse_scat_source) < 150);

ALTER TABLE buildings ADD COLUMN IF NOT EXISTS current_landuse_scat_source_detail varchar;
ALTER TABLE buildings ADD CONSTRAINT current_landuse_scat_source_detail_len CHECK (length(current_landuse_scat_source_detail) < 500);

ALTER TABLE buildings ADD COLUMN IF NOT EXISTS current_landuse_scat_link text[];
